name: Create issue on commit

on: [ push ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://githubaction.atlassian.net/rest/api/2/issue/'
          method: 'POST'
          username: 'khl.sakshi55@gmail.com'
          password: 'ATATT3xFfGF0Np7Ehac9J1Z4JNzUgSSLKf-FyxREEIXfzL4-7_Rlgj8K-SJQN_oNkbMgOBKmBQi_-H8SUThey-vGvl7H1VVbjdEeRt71LLe4C3cUilMN0_046Lnj76hu54SGN8dmGwVgJ_gQkztZkb8hjyeDQCulyoG8cwxKmHUm_by4ipnLHvM=257E828A'
          data: '{"fields": {"project": {"id": 10000 },"summary": "Creating rest api  github action 7.",  "description": "Creating of an issue using project keys and issue type names using the REST API","issuetype": {"name": "Bug"}}}'
         
