name: CI
on: [pull_request]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: hello
        run: <any> 
        continue-on-error: true
      - name: Step 2
        id: world
        run: <any> 
        continue-on-error: true
      - name: Check on failures
        if: steps.hello.outcome != 'success' || steps.world.outcome != 'success'
        run: exit 1
      - name: check split
        run: |
          MYPATH=/a/very/long/path/to/somewhere/sampleName.bam 
          echo $MYPATH
          MYFILE=${MYPATH##*/}
          echo $MYFILE
          MYSAMPLE=${MYFILE%.*}
          echo $MYSAMPLE
        
